
spawn:
  world: "world"
  x: 1
  y: 1
  z: 1
  yaw: 1
  pitch: 1

Arenas:
  bella: #Nome della arena
    min-players: 1
    #Il massimo sono il numero di spawns
    spawns:
      1:
        world: "world"
        x: 1
        y: 1
        z: 1
        yaw: 1
        pitch: 1
      2:
        world: "world"
        x: 1
        y: 1
        z: 1
        yaw: 1
        pitch: 1
      3:
        world: "world"
        x: 1
        y: 1
        z: 1
        yaw: 1
        pitch: 1
      4:
        world: "world"
        x: 1
        y: 1
        z: 1
        yaw: 1
        pitch: 1
  brutta:
    min-players: 2
    #Il massimo sono il numero di spawns
    spawns:
      1:
        world: "world"
        x: 1
        y: 1
        z: 1
        yaw: 1
        pitch: 1
      2:
        world: "world"
        x: 1
        y: 1
        z: 1
        yaw: 1
        pitch: 1
      3:
        world: "world"
        x: 1
        y: 1
        z: 1
        yaw: 1
        pitch: 1
      4:
        world: "world"
        x: 1
        y: 1
        z: 1
        yaw: 1
        pitch: 1